#!/bin/bash

lib=""
if [ "$1" == "lua" ]; then
  lib="main.lua"
elif [ "$1" == "rust" ]; then
  lib="main.rs"
elif [ "$1" == "cpp" ]; then
  lib="main.cc"
elif [ "$1" == "py" ]; then
  lib="main.py"
else
  echo "Language not specified"
  exit 1
fi

if [ "$2" == "-f" ]; then
  cp /Users/hobo/Develop/playground/atcoder/lib/"$lib" "$3"
else
  arr=( `ascl $2 $3` )
  failure=1

  for i in ${arr[@]}; do
    mkdir -p $i
    if [ "$?" == "$failure" ]; then
      echo "failed"
      exit 1
    fi
    cp /Users/hobo/Develop/playground/atcoder/lib/"$lib" "$i"
  done
fi
